### ISSUE TITLE
Improving installation instructions

### ISSUE THREAD

**Issue by AntonPetrov** [JossinetLab/RNA-Science-Toolbox#1]
Hi Fabrice,

Great work on packaging everything in a virtual box, way to go!

Just wanted to point out that if you do `vagrant ssh` and then `pyrna_tests.py` (as suggested in the README) the command will not be found and even when one locates `pyrna_tests.py` and runs it directly the script won't be able to import PyRNA modules because it won't be able to find `pyrna.db` etc. Same with running  `server.py`. 

You might want to update Readme and play with PYTHONPATH or maybe there is another solution.

Anton

**Comment by fjossinet** [comment]
Hi Anton,

Yes, you're right. The modifications i did recently broke some stuff. I'm writing some scripts to automate the build of a new virtual machine (based on the tool fabric). I'm planning to release it tomorrow. As a quick and dirty fix, once logged in the virtual machine, you can edit the file .zshrc to set the PYTHONPATH like that:

export PYTHONPATH=/vagrant

It should work.

Thanx for the highlight.

Fabrice

**Comment by AntonPetrov** [comment]
Hi Fabrice,

The latest changes fix the problem with running the tests (you might want to mention in Readme that one needs to `cd` to PyRNA before running tests) but when I try to access the server I see the following error on the console:

```
ERROR:tornado.application:Uncaught exception
Traceback (most recent call last):
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 236, in _read_message
    delegate.finish()
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/tornado/httpserver.py", line 267, in finish
    self.server.request_callback(self.request)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./server.py", line 26, in webservices
    return render_template('webservices.html')
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/vagrant/anaconda/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: webservices.html
```

Hope this helps!

I am interested in using this work as an example for making it easier to develop RNA 3D Hub in a distributive way so that people can clone the repo and use vagrant to get a working configuration of Apache, MySQL, Php etc. Virtualisation is very important, and it would be great to get people using it for RNA tools!

Anton

**Comment by fjossinet** [comment]
Hi Anton, 

the [new virtual machine is available](https://atlas.hashicorp.com/fjossinet/boxes/RnaSciToolbox). You have to update the git project, then vagrant up, vagrant ssh. Let me know. F

**Comment by AntonPetrov** [comment]
Everything is working out of the box now! I will close this and let you know if I discover any problems in a new issue.

Many thanks!

**Comment by fjossinet** [comment]
Thank you Anton. It's great to have feedback.
